### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Eaphan** [poodarchu/EFG#1]
Congratulation on the acceptance of ConQueR. I'm very interested in your work. When will you release your code?

**Comment by poodarchu** [comment]
Thanks for your interest in our work. Code will be released before CVPR23 camera-ready deadline (Mar 24 '23 11:59 PM PDT), stay tuned~

**Comment by Eaphan** [comment]
Well, thanks.

**Comment by Eaphan** [comment]
Can you send me your code before the official release if it's convenient? My email is yfzhang25@gmail.com. I can't wait to learn about your masterpiece. The performance is not quite important. Thank you very much. @poodarchu

**Comment by poodarchu** [comment]
Code has been released.
