### ISSUE TITLE
The code of TrajectoryFormer on nuScenes dataset

### ISSUE THREAD

**Issue by CBY-9527** [poodarchu/EFG#10]
This is a great work, thanks for sharing the code. The paper has always been experimentally verified on the nuScenes data set. I wonder if you can provide the relevant code of this method in the nuScenes data set, thank you.

**Comment by poodarchu** [comment]
https://github.com/V2AI/EFG/blob/master/playground/tracking.3d/waymo/trajectoryformer/README.md
