### ISSUE TITLE
About the sparse detectors in paper.

### ISSUE THREAD

**Issue by AlmoonYsl** [poodarchu/EFG#2]
I found that the CenterFormer is categorized as the dense detector in Table 1. But as far as I know, the CenterFormer uses 500/1000 queries produced by the topK method to detect objects on BEV features, so I think it should be a sparse method. I don't know if there is a mistake in my understanding, how do you define the sparse detectors in your paper?

**Comment by poodarchu** [comment]
CenterFormer is indeed a dense detector, it cannot work reasonably without post processing.

In Sec 4.2 of CenterFormer, it said:

During evaluation, we use the NMS IoU threshold of [0.8, 0.55, 0.55] and β = [1, 1, 4] for vehicle, pedestrian and cy- clist. For our 8 frames model, we use β = [1, 1, 1] to get a better result for the cyclist. We also increase the center proposal number N to 1000 in evaluation.

Moreover, the decoder layers only conduct bounding box refinement, which means all candidates' categories has already been determined in its center-point head.

**Comment by AlmoonYsl** [comment]
> CenterFormer is indeed a dense detector, it cannot work reasonably without post processing.
> 
> In Sec 4.2 of CenterFormer, it said:
> 
> During evaluation, we use the NMS IoU threshold of [0.8, 0.55, 0.55] and β = [1, 1, 4] for vehicle, pedestrian and cy- clist. For our 8 frames model, we use β = [1, 1, 1] to get a better result for the cyclist. We also increase the center proposal number N to 1000 in evaluation.
> 
> Moreover, the decoder layers only conduct bounding box refinement, which means all candidates' categories has already been determined in its center-point head.

Thanks for your reply! 
Did you test the CenterFormer without NMS? I'm curious about the results. ConQueR uses the NMS for better results, which achieves ~1 mAP improvements.

CenterFormer uses the heatmap to get queries by topK method, which already gets all candidates' categories, I don't think it is important for the definition of sparse detectors.

**Comment by poodarchu** [comment]
Sparse Detectors refer to detectors that can directly generate sparse predictions, which is a broad consensus in the research community. Besides, the sparse prediction property is guaranteed by one-to-one matching. That's the essential reason why ConQueR can achieve direct sparse predictions. However, CenterFormer still adopts traditional label assignment strategies with dense supervisions.

  From this point of view, ConQueR w/o NMS already surpasses previous SOTA by large margins. Moreover, NMS only contributes to Pedestrians, and harms the performance of Vehicle and Cyclist (See Appendix). We believe that this indicates the sparse predictions of ConQueR can be further improved. In Table 3, we showed that as the performance of ConQueR getting better, the average number of predictions per scene is decreasing as well.

  I just wanted to point out another difference between CenterFormer and a typical DETR-based 2D / 3D detectors. The role its decoder plays is different from the common practice in DETRs. As you said, it's not relevant to what makes for a sparse detector.

**Comment by AlmoonYsl** [comment]
> Sparse Detectors refer to detectors that can directly generate sparse predictions, which is a broad consensus in the research community. Besides, the sparse prediction property is guaranteed by one-to-one matching. That's the essential reason why ConQueR can achieve direct sparse predictions. However, CenterFormer still adopts traditional label assignment strategies with dense supervisions.
> 
> From this point of view, ConQueR w/o NMS already surpasses previous SOTA by large margins. Moreover, NMS only contributes to Pedestrians, and harms the performance of Vehicle and Cyclist (See Appendix). We believe that this indicates the sparse predictions of ConQueR can be further improved. In Table 3, we showed that as the performance of ConQueR getting better, the average number of predictions per scene is decreasing as well.
> 
> I just wanted to point out another difference between CenterFormer and a typical DETR-based 2D / 3D detectors. The role its decoder plays is different from the common practice in DETRs. As you said, it's not relevant to what makes for a sparse detector.

Thanks! Congratulations to your work is accepted by CVPR23.
