### ISSUE TITLE
Duplicate codes

### ISSUE THREAD

**Issue by Eaphan** [poodarchu/EFG#3]
Thanks for sharing your concise and elegant framework.

When I try to understand the code of VoxelDETR, I found some code may be duplicate. It's unnecessary to execute the forward operation of decoder.detection_head twice.

https://github.com/poodarchu/EFG/blob/dedd7375eb02ef163bc04343973f8c35fc0e66f8/projects/detection.3d/waymo/conquer/VoxelDETR.waymo.res18.p3.box_only_with_3cat.bs6.epoch6/voxel_detr.py#L135

**Comment by poodarchu** [comment]
Yes. I leave it here for readability, and you can comment the one in voxel_detr.py / transformer.py. No effect to final performance.

**Comment by Eaphan** [comment]
Thanks for your reply
