### ISSUE TITLE
start training

### ISSUE THREAD

**Issue by zqy411470859** [poodarchu/EFG#4]
# cd playground/path/to/experiment/directory  This path does not exist.  May I ask how to start training？
I am debugging at '/EFG/cli/main. py' and I am missing the 'EFG/cli/config. yaml' file. May I know how to obtain this file？
In addition, can I inquire about how many GPUs this method uses.

**Comment by poodarchu** [comment]
`cd` to certain directory, e.g., playground/detection.3d/waymo/conquer/xxxxxxxxx.
then run `efg_run --num-gpus 8 (or other gpu nums)`
do not just copy and paste.
