### ISSUE TITLE
Where can I found the code for Query Contrast? 

### ISSUE THREAD

**Issue by exiawsh** [poodarchu/EFG#5]
Hi, thanks for your great work on ConQueR.
Where can I find the loss calculation section of Query Contrast? I think I may have missed something, please guide me.

**Comment by poodarchu** [comment]
https://github.com/poodarchu/EFG/blob/master/playground/detection.3d/waymo/conquer/README.md

**Comment by exiawsh** [comment]
> https://github.com/poodarchu/EFG/blob/master/playground/detection.3d/waymo/conquer/README.md

Hi, I want to know where can I find the InfoNCE loss in your implementation.

**Comment by poodarchu** [comment]
> > https://github.com/poodarchu/EFG/blob/master/playground/detection.3d/waymo/conquer/README.md
> 
> Hi, I want to know where can I find the InfoNCE loss in your implementation.

https://github.com/poodarchu/EFG/blob/master/playground/detection.3d/waymo/conquer/ConQueR.waymo.res18.p3.dn3.tau07.noised_only.bs6.epoch6/voxel_detr.py#L250
