### ISSUE TITLE
How to run ConQueR code?

### ISSUE THREAD

**Issue by yangrongkun** [poodarchu/EFG#6]
The command is "efg_run task", but how could I run the ConQueR code? 
Thank you.

**Comment by yangrongkun** [comment]
OK, I understand, just cd into the playground dir then run the command, but if I want to debug the code, is there a good methods？

**Comment by poodarchu** [comment]
`efg_run` operates on single GPU by default, if you want to inspect dataloaders, you can dynamically set dataloader.numworkers. for example:

`efg_run dataloader.num_workers 0`
